version: '2'

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  monitornet:
    name: monitornet

services:
  prometheus:
    networks:
      - monitornet
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - /home/michael/monitoring/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
#    command:
#      - /home/michael/monitoring/prometheus/prometheus.yml=/etc/prometheus/prometheus.yml
#      - /home/michael/monitoring/prometheus=/prometheus
    expose:
      - 9090
    ports:
      - 9090:9090
    depends_on:
      - cadvisor
      - snmp-exporter
      - node-exporter

  snmp-exporter:
    networks:
      - monitornet
    container_name: snmpexporter
    image: amkay/snmp_exporter
    volumes:
      - /home/michael/monitoring/snmp_exporter/:/etc/snmp_exporter/
    expose:
      - 9116

  node-exporter:
    networks:
      - monitornet
    container_name: nodeexporter
    image: prom/node-exporter
    expose:
      - 9100

  cadvisor:
    networks:
      - monitornet
    container_name: cadvisor
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080

  grafana:
    networks:
      - monitornet
    container_name: grafana
    image: grafana/grafana-enterprise
    depends_on:
      - prometheus
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
#    env_file:
#      - /home/michael/monitoring/grafana/config.env
